actions:
  - type: exec
    items:
      - 'mkdir data'
      - 'mkdir data2'
  - type: install
    items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - git
  - type: exec
    items:
      - 'echo "testing1234" >> data/README.md'
      - 'echo $(whoami) >> data2/README.md'
      - 'wget --quiet -O - https://download.docker.com/linux/ubuntu/gpg | apt-key add -'
      - 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic stable"'
      - 'sudo apt-get update'
      - 'sudo apt-get install -y docker-ce docker-ce-cli docker-compose containerd.io'
      - 'sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
      - 'sudo chmod +x /usr/local/bin/docker-compose'
  - type: install
    items:
      - apache2
